# Server
server.port=8081

# MQTT
mqtt.broker.url=tcp://localhost:1883
mqtt.client.id=edge-server-locale-1

# Central Server
central.server.url=http://localhost:8080

# Database H2 locale (funziona anche offline)
spring.datasource.url=jdbc:h2:file:./edge-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console